<?php
namespace App\Controller;

use App\Controller\AppController;

/**
 * Class GeneralController
 * @package App\Controller
 */
class GeneralController extends AppController
{
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->modelClass = false;
    }

    public function setting()
    {
        $this->loadModel('Settings');
        $settings = $this->Settings->retrieveMetas();
        $appLogo = $this->appsLogo;
        if ($this->request->is('post')) {
            $data = $this->request->data;
            if (isset($this->request->data['application_logo']['name']) && $this->request->data['application_logo']['name']) {
                $appLogo = $this->Utilities->uploadFile(WWW_ROOT . 'img/attachments', $this->request->data['application_logo'], 'logo');
                if($appLogo) {
                    $appLogo = explode('img/', $appLogo['path']);
                    $appLogo = $appLogo[1];
                }
            }
            $data['logo'] = $appLogo;
            unset($data['application_logo']);


            $isSaved = $this->Settings->registerMetaValues($data);
            if ($isSaved) {
                $this->Flash->success(__('Configuration has been updated successfully'));
            } else {
                $this->Flash->error(__('Sorry! something went wrong'));
            }
            return $this->redirect(['controller' => 'settings', 'action' => 'index']);
        }
        $this->set(compact('settings'));
    }
}
